name: CI
on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch: {}

jobs:
  call:
    uses: KirillBaranov/kb-labs-devkit/.github/workflows/ci-reusable.yml@main
    with:
      node-version: '20'
      run-coverage: true
